/**
 * Audit Workpaper Export Utility for LedgerDuck 2.0
 * Formats findings and ledger scrutiny evidence into standardized,
 * documentation-ready CSV workpapers.
 * Licensed under AGPL-3.0
 */

export interface WorkpaperMetadata {
  title: string;
  tableName: string;
  testObjective?: string;
  findingsCount: number;
}

/**
 * Escapes a single CSV field following RFC 4180.
 */
function escapeCsvCell(value: any): string {
  if (value === null || value === undefined) return '';
  const str = typeof value === 'object' ? JSON.stringify(value) : String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

/**
 * Sanitizes a single-line header value (strips CR/LF to prevent header injection).
 */
function sanitizeHeaderLine(value: string): string {
  return String(value ?? '').replace(/[\r\n]+/g, ' ').slice(0, 500);
}

/**
 * Generates formatted CSV string with audit workpaper header metadata.
 */
export function generateWorkpaperCsv(
  metadata: WorkpaperMetadata,
  headers: string[],
  rows: Record<string, any>[],
): string {
  const lines: string[] = [];
  const now = new Date().toISOString().replace('T', ' ').substring(0, 19);

  // Audit Workpaper Header block
  lines.push(`# ============================================================`);
  lines.push(`# AUDIT WORKPAPER: ${sanitizeHeaderLine(metadata.title)}`);
  lines.push(`# DATA SOURCE TABLE: ${sanitizeHeaderLine(metadata.tableName)}`);
  if (metadata.testObjective) {
    lines.push(`# AUDIT OBJECTIVE: ${sanitizeHeaderLine(metadata.testObjective)}`);
  }
  lines.push(`# GENERATED BY: LedgerDuck 2.0 Audit Laboratory`);
  lines.push(`# EXECUTION TIMESTAMP (UTC): ${now}`);
  lines.push(`# FINDINGS IDENTIFIED: ${metadata.findingsCount}`);
  lines.push(`# ============================================================`);
  lines.push('');

  // Table Column Headers
  lines.push(headers.map(escapeCsvCell).join(','));

  // Data rows
  for (const row of rows) {
    const rowValues = headers.map((h) => escapeCsvCell(row[h]));
    lines.push(rowValues.join(','));
  }

  return lines.join('\r\n');
}

/**
 * Triggers a browser download of a CSV file.
 */
export function downloadCsvFile(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename.endsWith('.csv') ? filename : `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  // Defer revoke: synchronous revoke aborts the download in Firefox/Safari.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
