export const LOCAL_STORAGE_KEYS = {
  RUN_QUERY_BUTTON_VALUE: 'RUN_QUERY_BUTTON_VALUE',
  MAX_CONNECTION_POOL_SIZE: 'MAX_CONNECTION_POOL_SIZE',
  MAIN_LAYOUT_DIMENSIONS: 'MAIN_LAYOUT_DIMENSIONS',
  SIDEBAR_COLLAPSED: 'SIDEBAR_COLLAPSED',
  ONBOARDING_SHOWN: 'ONBOARDING_SHOWN',
  WHATS_NEW_VERSION_SHOWN: 'WHATS_NEW_VERSION_SHOWN',
  AI_SERVICE_CONFIG: 'AI_SERVICE_CONFIG',
  BROWSER_COMPATIBILITY_DISMISSED: 'BROWSER_COMPATIBILITY_DISMISSED',
  CORS_PROXY_SETTINGS: 'CORS_PROXY_SETTINGS',
  POLLY_DEMO_BANNER_DISMISSED: 'POLLY_DEMO_BANNER_DISMISSED',
  AUDIT_PANEL_OPEN: 'AUDIT_PANEL_OPEN',
  ACTIVE_ROOM: 'ACTIVE_ROOM',
  GETTING_STARTED_DISMISSED: 'LEDGERDUCK_GETTING_STARTED_DISMISSED',
  FIRST_CHECK_RUN: 'LEDGERDUCK_FIRST_CHECK_RUN',
  VOCAB_CUSTOM_STOPWORDS: 'LEDGERDUCK_VOCAB_STOPWORDS',
  VOCAB_SYNONYM_GROUPS: 'LEDGERDUCK_VOCAB_SYNONYMS',
  VOCAB_UBO_RULES: 'LEDGERDUCK_VOCAB_UBO_RULES',
};

export const SESSION_STORAGE_KEYS = {
  FALLBACK_MODE_WARNING_SHOWN: 'FALLBACK_MODE_WARNING_SHOWN',
};
